source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TCSDAL_Example', :exclusive => true do
  pod "TCSDAL", :path => "../"
end

target 'TCSDAL_Tests', :exclusive => true do
  pod "TCSDAL", :path => "../"

  pod 'Kiwi'
end
