source 'https://github.com/CocoaPods/Specs.git'

target 'TCSDAL_Example', :exclusive => true do
  pod "TCSDAL", :path => "../"
end

target 'TCSDAL_Tests', :exclusive => true do
  pod "TCSDAL", :path => "../"

  pod 'Kiwi'
end
